### ISSUE TITLE
Invisible reCaptcha and reCaptcha V2 is confusing

### ISSUE THREAD

**Issue by razvanaldea89** [razvanaldea89/uber-recaptcha#10]
There are currently 2 versions of reCaptcha, V3 and V2, with V2 having 3 types, so it is a little confusing

**Comment by cristianraiber** [comment]
@razvanaldea89 - what solution do you propose?

**Comment by razvanaldea89** [comment]
@cristianraiber tell the user that they are reCaptcha V2 both and one is "Invisible" and one is "I'm not a robot" reCaptcha.

**Comment by cristianraiber** [comment]
I think that's a good idea!

**Comment by razvanaldea89** [comment]
Already launched.
